title: <p align="center"> Prashant Mohan Sinha </p>
logo: /assets/img/Me_SeismicAcquisition.jpg

description: 
  <p align="center">
  <a href="pdf/Resume.pdf">Resume</a> |
  <a href="linkedin.com/in/prashant-sinha-06a297b/">LinkedIn</a> |
  <a href="https://github.com/sinhapm">GitHub</a>
  <br>   
  I am an Sr. Geophysicist with 16 years of experience. 
  I have developed practical skill and knowledge in integrated geoscience exploration activities.
  <br>
  
  </p>
